default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  username: <%= ENV["URL_SHORTENER_LOCAL_DATABASE_USERNAME"] %>
  password: <%= ENV["URL_SHORTENER_LOCAL_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: url_shortener_development
  host: localhost

test:
  <<: *default
  database: url_shortener_test
  host: localhost

production:
  <<: *default
  database: url_shortener_production
  username: url_shortener
  password: <%= ENV["URL_SHORTENER_DATABASE_PASSWORD"] %>
